from typing import Literal, cast

AlertResponseDataSource = Literal[
    "alertmanager",
    "api",
    "app_dynamics",
    "app_optics",
    "asana",
    "azure",
    "bug_snag",
    "catchpoint",
    "checkly",
    "chronosphere",
    "clickup",
    "cloud_watch",
    "datadog",
    "email",
    "generic_webhook",
    "gitlab",
    "google_cloud",
    "grafana",
    "heartbeat",
    "honeycomb",
    "jira",
    "linear",
    "live_call_routing",
    "manual",
    "mobile",
    "monte_carlo",
    "nagios",
    "new_relic",
    "nobl9",
    "opsgenie",
    "pagerduty",
    "pagertree",
    "prtg",
    "rollbar",
    "rootly",
    "sentry",
    "service_now",
    "slack",
    "splunk",
    "victorops",
    "web",
    "workflow",
    "zendesk",
]

ALERT_RESPONSE_DATA_SOURCE_VALUES: set[AlertResponseDataSource] = {
    "alertmanager",
    "api",
    "app_dynamics",
    "app_optics",
    "asana",
    "azure",
    "bug_snag",
    "catchpoint",
    "checkly",
    "chronosphere",
    "clickup",
    "cloud_watch",
    "datadog",
    "email",
    "generic_webhook",
    "gitlab",
    "google_cloud",
    "grafana",
    "heartbeat",
    "honeycomb",
    "jira",
    "linear",
    "live_call_routing",
    "manual",
    "mobile",
    "monte_carlo",
    "nagios",
    "new_relic",
    "nobl9",
    "opsgenie",
    "pagerduty",
    "pagertree",
    "prtg",
    "rollbar",
    "rootly",
    "sentry",
    "service_now",
    "slack",
    "splunk",
    "victorops",
    "web",
    "workflow",
    "zendesk",
}


def check_alert_response_data_source(value: str | None) -> AlertResponseDataSource | None:
    if value is None:
        return None
    if value in ALERT_RESPONSE_DATA_SOURCE_VALUES:
        return cast(AlertResponseDataSource, value)
    raise TypeError(f"Unexpected value {value!r}. Expected one of {ALERT_RESPONSE_DATA_SOURCE_VALUES!r}")
