from typing import Literal

AlertEventAction = Literal[
    "ack_timeout_retriggered",
    "acknowledged",
    "added",
    "answered",
    "attached",
    "call_lifecycle",
    "called",
    "cleared",
    "created",
    "deferred",
    "emailed",
    "escalated",
    "escalation_policy_paged",
    "google_chat_messaged",
    "ignored_alert_request",
    "level_skipped",
    "marked",
    "ms_teams_messaged",
    "muted",
    "not_marked",
    "notified",
    "open",
    "opened",
    "paged",
    "removed",
    "resolved",
    "retrigger_cancelled",
    "retrigger_suppressed",
    "retriggered",
    "skipped",
    "slacked",
    "snoozed",
    "team_attached_from_payload",
    "texted",
    "triggered",
    "updated",
    "user_paged",
]

ALERT_EVENT_ACTION_VALUES: set[AlertEventAction] = {
    "ack_timeout_retriggered",
    "acknowledged",
    "added",
    "answered",
    "attached",
    "call_lifecycle",
    "called",
    "cleared",
    "created",
    "deferred",
    "emailed",
    "escalated",
    "escalation_policy_paged",
    "google_chat_messaged",
    "ignored_alert_request",
    "level_skipped",
    "marked",
    "ms_teams_messaged",
    "muted",
    "not_marked",
    "notified",
    "open",
    "opened",
    "paged",
    "removed",
    "resolved",
    "retrigger_cancelled",
    "retrigger_suppressed",
    "retriggered",
    "skipped",
    "slacked",
    "snoozed",
    "team_attached_from_payload",
    "texted",
    "triggered",
    "updated",
    "user_paged",
}


def check_alert_event_action(value: str | None) -> AlertEventAction | None:
    if value is None:
        return None
    if value in ALERT_EVENT_ACTION_VALUES:
        return value
    raise TypeError(f"Unexpected value {value!r}. Expected one of {ALERT_EVENT_ACTION_VALUES!r}")
